version: '3.9'
name: ONIS_Application
services:
  #########################
  # APIS configuration    #
  #########################
  webapp:
    container_name: ApiCatalog
    build:
      context: .
      dockerfile: ONIS.API.Catalog/Dockerfile
    ports:
      - "5102:80"
      - "7006:443" #aun no he configurado el https
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS	https://+:443;http://+:80
   

      #- ASPNETCORE_HTTPS_PORT=7006- DOTNET_RUNNING_IN_CONTAINERtrue estalinea temporalmente detenida #
  ##########################
  # APIS configuration end #
  ##########################
  ##########################
  # Databases for APIS     #
  ##########################
  msqlserv:
    container_name: mssqlsevdb
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      MSSQL_SA_PASSWORD: "TUC:GR8?MHYP"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"           
    volumes:
      - ../volumens/mssql/sqlserver_data:/var/opt/mssql/data
    ports:
      - "1433:1433"
  ##########################
  # Databases for APIS     #
  ##########################
  #########################
  # Graylog configuration #
  #########################
  # mongo should be called mongo
  mongo:
    container_name: mongo_graylog
    image: mongo:4.2
  elasticsearch:
    container_name: elasticserach_graylog
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
  graylog:
    image: graylog/graylog:4.2.5
    container_name: graylog
    environment:
      # at least 16 characters
      - GRAYLOG_PASSWORD_SECRET=thispassshouldbeatleast16characters
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9000/
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - 9000:9000 # Graylog web interface and REST API
      - 1514:1514
      - 1514:1514/udp
      - 12201:12201
      - 12201:12201/udp
  #############################
  # Graylog configuration end #
  #############################
       
      